### ISSUE TITLE
FSDP RuntimeError: 'weight' must be 2-D

### ISSUE THREAD

**Issue by mukhayy** [huggingface/transformers#39186]
I am getting `'weight' must be 2-D` error when full fine tuning gemma-3-12b on 4xGPU. Couple of days back with the same configuration I was not getting this error, I verified I haven't changed anything since.

FSDP conf inside TrainingArguments()

```
fsdp="full_shard",
fsdp_config={
                "auto_wrap_policy": "transformer_based_wrap",
                "backward_prefetch": "backward_pre",
                "cpu_ram_efficient_loading": True,
                "use_orig_params": True,
                "sync_module_states": True,
                "transformer_layer_cls_to_wrap": ["Gemma3DecoderLayer"],
            },
```

Stack Trace

```
2025-07-03 04:54:34,137 - ERROR - Traceback (most recent call last):
  File "/mnt/dataset/working_fsdp.py", line 304, in main
    trainer.train()
  File "/opt/conda/lib/python3.12/site-packages/transformers/trainer.py", line 2207, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/trainer.py", line 2549, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/trainer.py", line 3750, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/trainer.py", line 3837, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/accelerate/utils/operations.py", line 818, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/accelerate/utils/operations.py", line 806, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/models/gemma3/modeling_gemma3.py", line 1083, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/utils/generic.py", line 943, in wrapper
    output = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/models/gemma3/modeling_gemma3.py", line 885, in forward
    inputs_embeds = self.get_input_embeddings()(llm_input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/transformers/models/gemma3/modeling_gemma3.py", line 113, in forward
    return super().forward(input_ids) * self.embed_scale.to(self.weight.dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 192, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/torch/nn/functional.py", line 2546, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 'weight' must be 2-D
```

Anyone has pointers where the issue might be?
Thanks

**Comment by IlyasMoutawwakil** [comment]
please install from main and test again, the issue should be fixed with #39152

**Comment by kmehant** [comment]
@IlyasMoutawwakil This (https://github.com/huggingface/transformers/pull/39177) is much more correct fix for this. Since it would not break for TP as well. Thanks

**Comment by muhayyo-tash** [comment]
Thanks latest release resolved this issue

**Comment by danielm1405** [comment]
I still encounter this issue. I try to run (a slightly modified) [alignment-handbook/scripts/sft.py](https://github.com/huggingface/alignment-handbook/blob/main/scripts/sft.py) with [this accelerate config](https://github.com/huggingface/alignment-handbook/blob/main/recipes/accelerate_configs/fsdp.yaml) using `transformers==4.56.2` and end up with basically the same error trace as OP for both `Qwen/Qwen2.5-0.5B` and `meta-llama/Llama-3.1-8B`:

```
  File "/project/6104653/dmarczak/instruction-merging/sft.py", line 188, in <module>
    main(script_args, training_args, model_args)
  File "/project/6104653/dmarczak/instruction-merging/sft.py", line 136, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/trainer.py", line 2328, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/trainer.py", line 2672, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 1189, in training_step
    return super().training_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/trainer.py", line 4009, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 1103, in compute_loss
    (loss, outputs) = super().compute_loss(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/trainer.py", line 4099, in compute_loss
    outputs = model(**inputs)
              ^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/accelerate/utils/operations.py", line 818, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/accelerate/utils/operations.py", line 806, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/utils/generic.py", line 940, in wrapper
    output = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 449, in forward
    outputs: BaseModelOutputWithPast = self.model(
                                       ^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/utils/generic.py", line 1064, in wrapper
    outputs = func(self, *args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 345, in forward
    inputs_embeds = self.embed_tokens(input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/project/6104653/dmarczak/instruction-merging/handbook/lib/python3.11/site-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: 'weight' must be 2-D
```

**Comment by yurkoff-mv** [comment]
I faced the [same problem](https://github.com/huggingface/accelerate/issues/3825).

**Comment by szhou0202** [comment]
I got the same issue when trying to do SFT using Llamafactory and deepspeed on Qwen3-8B-Base
