### ISSUE TITLE
Unable to install Transformers Master version

### ISSUE THREAD

**Issue by AnkitVarshney02** [huggingface/transformers#6752]
I want to run Pegasus Model for which master version of transformers is required but I am unable install it.
I tried installing with pip command but it always install version 3.0.2.

**Comment by andrei-volkau** [comment]
The problem with the current `master` is that I have the following error

`ModuleNotFoundError: No module named 'transformers.utils'`

 `version 3.0.2` does not include Pegasus.

Can anyone suggest to us the latest stable version of master (not release `version 3.0.2`)? So we will be able to run the Pegasus Model.

**Comment by patil-suraj** [comment]
`pip install -U git+https://github.com/huggingface/transformers.git`

**Comment by abelriboulot** [comment]
I actually think this is a breaking change which @joeddav seems to have fixed in his PR. It is due to a change 6 hours ago which makes the import of the utils [here](https://github.com/huggingface/transformers/blob/master/src/transformers/file_utils.py) fail!

**Comment by joeddav** [comment]
K, import issue is fixed by #6754 and installs from master as @patil-suraj mentioned should be good now.

**Comment by AnkitVarshney02** [comment]
Is there some other way to install master version of transformers?

I tried using the URL but encountered error msg as mentioned below:
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
So, I tried installing Git to Path folder but still facing the same issue.

Tool used for coding: Microsoft Visual Studio code

**Comment by joeddav** [comment]
@AnkitVarshney02 

1. Since master is not tagged as a release it will still register as `3.02` in your environment when you've installed from master.
2. If you already have transformers installed in your env make sure you're also passing `--upgrade`

`pip install --upgrade git+https://github.com/huggingface/transformers.git`

**Comment by AnkitVarshney02** [comment]
@joeddav 
I tried using the URL to install the master version but it again installed v3.0.2.

**Comment by joeddav** [comment]
Master isn't tagged with its own release, so it will actually still show as `3.02` right now even if you've installed from master correctly. Did you try importing Pegasus after the above?

**Comment by AnkitVarshney02** [comment]
> Master isn't tagged with its own release, so it will actually still show as `3.02` right now even if you've installed from master correctly. Did you try importing Pegasus after the above?

Thanks @joeddav ! It is working!!
