### ISSUE TITLE
Keyword arguments {'add_prefix_space': False} not recognized.

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8322]
Hi
I am getting  this message when running finetune_trainer.py on TPUs any idea how to remove it? thanks

**Comment by LysandreJik** [comment]
Hi @rabeehkarimimahabadi. Could you please respect the issue template when opening issues? It is necessary for us to help you, otherwise we'll have to ask again and again for you to provide more information.

Please complete the issue template with the information related to your environment, to the command you launched, and the full error with the stack trace. Thanks.

**Comment by rabeehkarimimahabadi** [comment]
Hi
I am sorry
here is the full command I use , it is running finetune_trainer with T5
model. There is not an error, only it gives this warning. thanks


python xla_spawn.py --num_cores 8 finetune_trainer.py
--learning_rate=3e-5         --n_val 1000  --model_name_or_path t5-small
--data_dir data/wmt_en_de/ --output_dir /home/rabeeh/temp/
--overwrite_output_dir  --tpu_num_cores=8 --max_source_length=64
--max_target_length=64 --per_device_train_batch_size=32
--per_device_eval_batch_size=32 --label_smoothing=0.1 --task="translation"
--logging_steps=200 --eval_steps=500 --num_train_epochs=6 --save_steps=500
--max_source_length=128  --max_target_length=128
--val_max_target_length=128 --test_max_target_length=128

**Comment by LysandreJik** [comment]
Since you're using the T5 model I believe you can safely ignore that warning, which is useful only for the byte-level BPE tokenizers (think GPT-2, RoBERTa).

Maybe @patil-suraj or @sshleifer know why such a warning is thrown when using T5 with the `Seq2SeqTrainer`

**Comment by sshleifer** [comment]
Yeah it's happening in seq2seq dataset, you can safely ignore. Fixed in #8329

**Comment by rabeehkarimimahabadi** [comment]
Hi,
thank you. Is this applied to the repo? thanks

**Comment by LysandreJik** [comment]
Yes, the fix has just been merged.

**Comment by rabeehkarimimahabadi** [comment]
Hi there, this is not fixed for me. and still I am getting it with running T5 using finetune_trainer.

**Comment by LysandreJik** [comment]
Have you pulled from `master` to get the updated version?

In any case, as I've said before, this is a warning and not an error. You can safely ignore it.
